(* generated by dune *)

(** @canonical Bimage.Color *)
module Color = Bimage__Color

(** @canonical Bimage.Data *)
module Data = Bimage__Data

(** @canonical Bimage.Error *)
module Error = Bimage__Error

(** @canonical Bimage.Expr *)
module Expr = Bimage__Expr

(** @canonical Bimage.Filter *)
module Filter = Bimage__Filter

(** @canonical Bimage.Hash *)
module Hash = Bimage__Hash

(** @canonical Bimage.Image *)
module Image = Bimage__Image

(** @canonical Bimage.Input *)
module Input = Bimage__Input

(** @canonical Bimage.Kernel *)
module Kernel = Bimage__Kernel

(** @canonical Bimage.Pixel *)
module Pixel = Bimage__Pixel

(** @canonical Bimage.Transform *)
module Transform = Bimage__Transform

(** @canonical Bimage.Type *)
module Type = Bimage__Type

(** @canonical Bimage.Util *)
module Util = Bimage__Util
