(* generated by dune *)

(** @canonical Parser_extended.Ast_helper *)
module Ast_helper = Parser_extended__Ast_helper

(** @canonical Parser_extended.Ast_mapper *)
module Ast_mapper = Parser_extended__Ast_mapper

(** @canonical Parser_extended.Asttypes *)
module Asttypes = Parser_extended__Asttypes

(** @canonical Parser_extended.Docstrings *)
module Docstrings = Parser_extended__Docstrings

(** @canonical Parser_extended.Lexer *)
module Lexer = Parser_extended__Lexer

(** @canonical Parser_extended.Parse *)
module Parse = Parser_extended__Parse

(** @canonical Parser_extended.Parser *)
module Parser = Parser_extended__Parser

(** @canonical Parser_extended.Parsetree *)
module Parsetree = Parser_extended__Parsetree

(** @canonical Parser_extended.Printast *)
module Printast = Parser_extended__Printast
