(* generated by dune *)

(** @canonical Parser_standard.Ast_helper *)
module Ast_helper = Parser_standard__Ast_helper

(** @canonical Parser_standard.Ast_mapper *)
module Ast_mapper = Parser_standard__Ast_mapper

(** @canonical Parser_standard.Asttypes *)
module Asttypes = Parser_standard__Asttypes

(** @canonical Parser_standard.Docstrings *)
module Docstrings = Parser_standard__Docstrings

(** @canonical Parser_standard.Lexer *)
module Lexer = Parser_standard__Lexer

(** @canonical Parser_standard.Parse *)
module Parse = Parser_standard__Parse

(** @canonical Parser_standard.Parser *)
module Parser = Parser_standard__Parser

(** @canonical Parser_standard.Parsetree *)
module Parsetree = Parser_standard__Parsetree

(** @canonical Parser_standard.Printast *)
module Printast = Parser_standard__Printast
