(* generated by dune *)

(** @canonical Ocaml_common.Location *)
module Location = Ocaml_common__Location

(** @canonical Ocaml_common.Longident *)
module Longident = Ocaml_common__Longident

(** @canonical Ocaml_common.Syntaxerr *)
module Syntaxerr = Ocaml_common__Syntaxerr

(** @canonical Ocaml_common.Warnings *)
module Warnings = Ocaml_common__Warnings
